version: '3.5'

volumes:
  wiremock-data:
  rabbit-data:
  redis-data:

networks:
  proxynet:
    name: parkun

services:
  redis:
    container_name: parkun_redis
    image: redis:5.0.7-alpine
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    ports:
      - 16379:6379
    volumes:
      - redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - proxynet

  rabbit:
    container_name: parkun_rabbit
    networks:
      - proxynet
    ports:
      - 5672:5672
      - 15672:15672
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    restart: always
    hostname: parkun_rabbit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  numberplate:
    container_name: parkun_numberplate
    image: skaborik/numberplate_by
    networks:
      - proxynet
    ports:
      - 5001:80
    volumes:
      - /tmp/temp_files_parkun:/tmp/temp_files_parkun
    restart: always
    hostname: parkun_numberplate
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=0
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80

  wiremock:
    container_name: parkun_wiremock
    image: rodolpheche/wiremock:2.25.0-alpine
    networks:
      - proxynet
    ports:
      - 18080:8080
    volumes:
      - wiremock-data:/home/wiremock
      - ./wiremock/mappings:/home/wiremock/mappings
