version: '3'

volumes:
  redis-data:
  wiremock-data:
  rabbit-data:

networks:
  parkun:

services:
  redis:
    container_name: parkun_redis
    image: redis:alpine3.10
    command: redis-server --requirepass 'redis'
    ports:
      - 16379:6379
    volumes:
      - redis-data:/data
    networks:
      - parkun

  wiremock:
    container_name: parkun_wiremock
    image: rodolpheche/wiremock:2.25.0-alpine
    networks:
      - parkun
    ports:
      - 18080:8080
    volumes:
      - wiremock-data:/home/wiremock
      - ./wiremock/mappings:/home/wiremock/mappings

  rabbit:
    container_name: parkun_rabbit
    networks:
      - parkun
    ports:
      - 5672:5672
      - 15672:15672
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

